NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/org2-ca-example-com-7057-ca-org2.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/org2-ca-example-com-7057-ca-org2.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/org2-ca-example-com-7057-ca-org2.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/org2-ca-example-com-7057-ca-org2.pem
    OrganizationalUnitIdentifier: orderer
