version: '2'

volumes:
  orderer-tls.ca.example.com:

networks:
  byfn:
    external:
      name: first-network

services:

  orderer-tls.ca.example.com:
    container_name: orderer-tls.ca.example.com
    image: hyperledger/fabric-ca:1.4.7
    command: sh -c 'fabric-ca-server start -b orderer-tls-ca-admin:orderer-tls-ca-adminpw --port 8055 -u https://root-ca-admin:root-ca-adminpw@root.ca.example.com:7054 --cfg.affiliations.allowremove --cfg.identities.allowremove'
    environment:
      - FABRIC_CA_SERVER_INTERMEDIATE_TLS_CERTFILES=/etc/hyperledger/fabric-ca-server/root-ca-cert.pem
      - FABRIC_CA_SERVER_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CSR_HOSTS=orderer-tls.ca.example.com
      - FABRIC_CA_SERVER_DEBUG=true
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server/ca-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server/msp/keystore/*_sk
      - FABRIC_CA_CLIENT_HOME=/etc/hyperledger/fabric-ca-client
      - FABRIC_CA_CLIENT_TLS_CERTFILES=/etc/hyperledger/fabric-ca-server/ca-cert.pem
    volumes:
      - ./fabric-ca-server/intermediacatls1:/etc/hyperledger/fabric-ca-server
      - ./fabric-ca-client/intermediacatls1:/etc/hyperledger/fabric-ca-client
    networks: 
      - byfn  
    ports:
      - 8055:8055
