version: '2'

volumes:
  root.ca.example.com:

networks:
  byfn:
    external:
      name: first-network

services:

  root.ca.example.com:
    container_name: root.ca.example.com
    image: hyperledger/fabric-ca:1.4.7
    command: sh -c 'fabric-ca-server start -d -b root-ca-admin:root-ca-adminpw --port 7054 --cfg.affiliations.allowremove --cfg.identities.allowremove'
    environment:
      - FABRIC_CA_SERVER_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CSR_CN=root.ca.example.com 
      - FABRIC_CA_SERVER_CSR_HOSTS=root.ca.example.com
      - FABRIC_CA_SERVER_DEBUG=true
    volumes:
      - ./fabric-ca-server/root-ca:/etc/hyperledger/fabric-ca-server      
    networks:       
      - byfn       
    ports:
      - 7054:7054
