NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/orderer-ca-example-com-7055-ca-orderer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/orderer-ca-example-com-7055-ca-orderer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/orderer-ca-example-com-7055-ca-orderer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/orderer-ca-example-com-7055-ca-orderer.pem
    OrganizationalUnitIdentifier: orderer
